language: r
cache: packages
r:
- bioc-release
r_packages:
- pkgdown
bioc_packages:
- HDF5Array
- preprocessCore
- DESeq2
r_github_packages:
- demuellae/muLogR
- demuellae/muReportR
- demuellae/muRtools
- demuellae/ChrAccR
- demuellae/ChrAccRex
addons:
  apt:
    packages:
    - libgsl0ldbl
    - libgsl0-dev
# r_build_args: --no-build-vignettes
# r_check_args: --no-build-vignettes
warnings_are_errors: false
# automatically build pkgdown site using the gh-pages branch
after_success:
  - Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
